name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests [OTP/Elixir]"
    env: 
      MIX_ENV: test
    services:
      ldap:
        image: osixia/openldap:latest
        ports:
          - 1636:636
          - 1389:389
    strategy:
      fail-fast: false
      matrix:
        otp: [24, 25, 26]
        elixir: [1.14, 1.15]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install dependecies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile project
        run: mix compile
      - name: Run tests
        run: mix test --include integration:true
